#name: GitHub Actions DevOps Center
#run-name: ${{ github.actor }} is a test to Devops Center 
#on: 
#  push:
#    branches:
#      - SIT
#    paths:
#      - 'force-app/**'
      
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "🔎 O job irá iniciar assim que for enviado um item para a branch de SIT."
#      - name: Verificação do código no repositório
#        uses: actions/checkout@v3

#     - run: echo "💡 O ${{ github.repository }} O repositório foi clonado para o runner"
#    - run: echo "🖥️ O workflow agora está pronto para rodar"
#      - name: Listar todos os arquivos do repositório
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "🍏 O status to job é ${{ job.status }}."
      
#  build:
#    runs-on: ubuntu-latest
#    environment: developer
#    steps:
      # Checkout the Source code from the latest commit
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
          
